COUNTRIES = [
    {"code": "AL", "name": "Albania", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "AM", "name": "Armenia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "AZ", "name": "Azerbaijan", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "BZ", "name": "Belize", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "BJ", "name": "Benin", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "BW", "name": "Botswana", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "BG", "name": "Bulgaria", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "BF", "name": "Burkina Faso", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "KH", "name": "Cambodia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "CM", "name": "Cameroon", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "CV", "name": "Cape Verde", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "CN", "name": "China", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "CO", "name": "Colombia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "CR", "name": "Costa Rica", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "DO", "name": "Dominican Republic", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "LC", "name": "Eastern Caribbean", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "SV", "name": "El Salvador", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "EC", "name": "Ecuador", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "ET", "name": "Ethopia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "FJ", "name": "Fiji", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GE", "name": "Georgia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GH", "name": "Ghana", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GT", "name": "Guatemala", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GN", "name": "Guinea", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GY", "name": "Guyana", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "HN", "name": "Honduras", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "ID", "name": "Indonesia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "JM", "name": "Jamaica", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "JO", "name": "Jordan", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "KZ", "name": "Kazakhstan", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "KE", "name": "Kenya", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "KG", "name": "Kyrgyz Republic", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "LS", "name": "Lesoto", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "LR", "name": "Liberia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MK", "name": "Macedonia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MG", "name": "Madagascar", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MW", "name": "Malawi", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "ML", "name": "Mali", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MX", "name": "Mexico", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "FM", "name": "Micronesia and Polynesia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MD", "name": "Moldova", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MN", "name": "Mongolia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MA", "name": "Morocco", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "MZ", "name": "Mozambique", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "NA", "name": "Namibia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "NP", "name": "Nepal", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "NI", "name": "Nicaragua", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "NE", "name": "Niger", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "PA", "name": "Panama", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "PY", "name": "Paraguay", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "PE", "name": "Peru", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "PH", "name": "Philipines", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "RO", "name": "Romania", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "RW", "name": "Rwanda", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "WS", "name": "Samoa", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "SN", "name": "Senegal", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "SL", "name": "Sierra Leone", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "ZA", "name": "South Africa", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "SR", "name": "Suriname", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "SZ", "name": "Swaziland", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "TZ", "name": "Tanzania", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "GM", "name": "The Gambia", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "TH", "name": "Thailand", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "TG", "name": "Togo", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "TO", "name": "Tnoga", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "UG", "name": "Uganda", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "UA", "name": "Ukraine", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "VU", "name": "Vanatu", "coords": (0.00, 1.11), "zoomlevel": 5},
    {"code": "ZM", "name": "Zambia", "coords": (0.00, 1.11), "zoomlevel": 5}
]

COUNTRY_CHOICES = [(v["name"], k) for k,v in COUNTRIES.items()]

STATES = (
    (u"AL", u"Alabama"),
    (u"AK", u"Alaska"),
    (u"AZ", u"Arizona"),
    (u"AR", u"Arkansas"),
    (u"CA", u"California"),
    (u"CO", u"Colorado"),
    (u"CT", u"Connecticut"),
    (u"DE", u"Delaware"),
    (u"FL", u"Florida"),
    (u"GA", u"Georgia"),
    (u"HI", u"Hawaii"),
    (u"ID", u"Idaho"),
    (u"IL", u"Illinois"),
    (u"IN", u"Indiana"),
    (u"IA", u"Iowa"),
    (u"KS", u"Kansas"),
    (u"KY", u"Kentucky"),
    (u"LA", u"Louisiana"),
    (u"ME", u"Maine"),
    (u"MD", u"Maryland"),
    (u"MA", u"Massachusetts"),
    (u"MI", u"Michigan"),
    (u"MN", u"Minnesota"),
    (u"MS", u"Mississippi"),
    (u"MO", u"Missouri"),
    (u"MT", u"Montana"),
    (u"NE", u"Nebraska"),
    (u"NV", u"Nevada"),
    (u"NH", u"New Hampshire"),
    (u"NJ", u"New Jersey"),
    (u"NM", u"New Mexico"),
    (u"NY", u"New York"),
    (u"NC", u"North Carolina"),
    (u"ND", u"North Dakota"),
    (u"OH", u"Ohio"),
    (u"OK", u"Oklahoma"),
    (u"OR", u"Oregon"),
    (u"PA", u"Pennsylvania"),
    (u"RI", u"Rhode Island"),
    (u"SC", u"South Carolina"),
    (u"SD", u"South Dakota"),
    (u"TN", u"Tennessee"),
    (u"TX", u"Texas"),
    (u"UT", u"Utah"),
    (u"VT", u"Vermont"),
    (u"VA", u"Virginia"),
    (u"WA", u"Washington"),
    (u"WV", u"West Virginia"),
    (u"WI", u"Wisconsin"),
    (u"WY", u"Wyoming"),
    (u"AS", u"American Samoa"),
    (u"DC", u"District of Columbia"),
    (u"FM", u"Federated States of Micronesia"),
    (u"GU", u"Guam"),
    (u"MH", u"Marshall Islands"),
    (u"MP", u"Northern Mariana Islands"),
    (u"PW", u"Palau"),
    (u"PR", u"Puerto Rico"),
    (u"VI", u"Virgin Islands")
)

GRADES = (
    ("K", "Kindergarden"),
    ("1", "1st Grade"),
    ("2", "2nd Grade"),
    ("3", "3rd Grade"),
    ("4", "4th Grade"),
    ("5", "5th Grade"),
    ("6", "6th Grade"),
    ("7", "7th Grade"),
    ("8", "8th Grade"),
    ("9", "9th Grade"),
    ("10", "10th Grade"),
    ("11", "11th Grade"),
    ("12", "12th Grade")
)

SECTORS = (
    ("edu", "Education"),
    ("health", "Health"),
    ("ced", "Community Economic Development"),
    ("env", "Environment"),
    ("yid", "Youth in Development"),
    ("agr", "Agriculture"),
    ("others", "Others")
)

KEYWORDS = (
    ("Dan", "Dance"),
    ("Mus", "Music"),
    ("WS", "Water Sanitation"),
    ("Sp", "Spanish"),
    ("Fr", "French"),
    ("Hol", "Holidays"),
    ("Cli", "Climate"),
    ("Ani", "Animals"),
    ("Fo", "Food"),
    ("Ag", "Agriculture"),
    ("Be", "Beekeeping")
)
