COUNTRIES = {
    "AL": {"name": "Albania", "coords": (0.00, 1.11), "zoomlevel": 5},
    "AM": {"name": "Armenia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "AZ": {"name": "Azerbaijan", "coords": (0.00, 1.11), "zoomlevel": 5},
    "BZ": {"name": "Belize", "coords": (0.00, 1.11), "zoomlevel": 5},
    "BJ": {"name": "Benin", "coords": (0.00, 1.11), "zoomlevel": 5},
    "BW": {"name": "Botswana", "coords": (0.00, 1.11), "zoomlevel": 5},
    "BG": {"name": "Bulgaria", "coords": (0.00, 1.11), "zoomlevel": 5},
    "BF": {"name": "Burkina Faso", "coords": (0.00, 1.11), "zoomlevel": 5},
    "KH": {"name": "Cambodia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "CM": {"name": "Cameroon", "coords": (0.00, 1.11), "zoomlevel": 5},
    "CV": {"name": "Cape Verde", "coords": (0.00, 1.11), "zoomlevel": 5},
    "CN": {"name": "China", "coords": (0.00, 1.11), "zoomlevel": 5},
    "CO": {"name": "Colombia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "CR": {"name": "Costa Rica", "coords": (0.00, 1.11), "zoomlevel": 5},
    "DO": {"name": "Dominican Republic", "coords": (0.00, 1.11), "zoomlevel": 5},
    "LC": {"name": "Eastern Caribbean", "coords": (0.00, 1.11), "zoomlevel": 5},
    "SV": {"name": "El Salvador", "coords": (0.00, 1.11), "zoomlevel": 5},
    "EC": {"name": "Ecuador", "coords": (0.00, 1.11), "zoomlevel": 5},
    "ET": {"name": "Ethopia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "FJ": {"name": "Fiji", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GE": {"name": "Georgia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GH": {"name": "Ghana", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GT": {"name": "Guatemala", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GN": {"name": "Guinea", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GY": {"name": "Guyana", "coords": (0.00, 1.11), "zoomlevel": 5},
    "HN": {"name": "Honduras", "coords": (0.00, 1.11), "zoomlevel": 5},
    "ID": {"name": "Indonesia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "JM": {"name": "Jamaica", "coords": (0.00, 1.11), "zoomlevel": 5},
    "JO": {"name": "Jordan", "coords": (0.00, 1.11), "zoomlevel": 5},
    "KZ": {"name": "Kazakhstan", "coords": (0.00, 1.11), "zoomlevel": 5},
    "KE": {"name": "Kenya", "coords": (0.00, 1.11), "zoomlevel": 5},
    "KG": {"name": "Kyrgyz Republic", "coords": (0.00, 1.11), "zoomlevel": 5},
    "LS": {"name": "Lesoto", "coords": (0.00, 1.11), "zoomlevel": 5},
    "LR": {"name": "Liberia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MK": {"name": "Macedonia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MG": {"name": "Madagascar", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MW": {"name": "Malawi", "coords": (0.00, 1.11), "zoomlevel": 5},
    "ML": {"name": "Mali", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MX": {"name": "Mexico", "coords": (0.00, 1.11), "zoomlevel": 5},
    "FM": {"name": "Micronesia and Polynesia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MD": {"name": "Moldova", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MN": {"name": "Mongolia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MA": {"name": "Morocco", "coords": (0.00, 1.11), "zoomlevel": 5},
    "MZ": {"name": "Mozambique", "coords": (0.00, 1.11), "zoomlevel": 5},
    "NA": {"name": "Namibia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "NP": {"name": "Nepal", "coords": (0.00, 1.11), "zoomlevel": 5},
    "NI": {"name": "Nicaragua", "coords": (0.00, 1.11), "zoomlevel": 5},
    "NE": {"name": "Niger", "coords": (0.00, 1.11), "zoomlevel": 5},
    "PA": {"name": "Panama", "coords": (0.00, 1.11), "zoomlevel": 5},
    "PY": {"name": "Paraguay", "coords": (0.00, 1.11), "zoomlevel": 5},
    "PE": {"name": "Peru", "coords": (0.00, 1.11), "zoomlevel": 5},
    "PH": {"name": "Philipines", "coords": (0.00, 1.11), "zoomlevel": 5},
    "RO": {"name": "Romania", "coords": (0.00, 1.11), "zoomlevel": 5},
    "RW": {"name": "Rwanda", "coords": (0.00, 1.11), "zoomlevel": 5},
    "WS": {"name": "Samoa", "coords": (0.00, 1.11), "zoomlevel": 5},
    "SN": {"name": "Senegal", "coords": (0.00, 1.11), "zoomlevel": 5},
    "SL": {"name": "Sierra Leone", "coords": (0.00, 1.11), "zoomlevel": 5},
    "ZA": {"name": "South Africa", "coords": (0.00, 1.11), "zoomlevel": 5},
    "SR": {"name": "Suriname", "coords": (0.00, 1.11), "zoomlevel": 5},
    "SZ": {"name": "Swaziland", "coords": (0.00, 1.11), "zoomlevel": 5},
    "TZ": {"name": "Tanzania", "coords": (0.00, 1.11), "zoomlevel": 5},
    "GM": {"name": "The Gambia", "coords": (0.00, 1.11), "zoomlevel": 5},
    "TH": {"name": "Thailand", "coords": (0.00, 1.11), "zoomlevel": 5},
    "TG": {"name": "Togo", "coords": (0.00, 1.11), "zoomlevel": 5},
    "TO": {"name": "Tnoga", "coords": (0.00, 1.11), "zoomlevel": 5},
    "UG": {"name": "Uganda", "coords": (0.00, 1.11), "zoomlevel": 5},
    "UA": {"name": "Ukraine", "coords": (0.00, 1.11), "zoomlevel": 5},
    "VU": {"name": "Vanatu", "coords": (0.00, 1.11), "zoomlevel": 5},
    "ZM": {"name": "Zambia", "coords": (0.00, 1.11), "zoomlevel": 5}
}

COUNTRY_CHOICES = [(v["name"], k) for k,v in COUNTRIES.items()]

STATES = (
    (u"AL", u"Alabama"),
    (u"AK", u"Alaska"),
    (u"AZ", u"Arizona"),
    (u"AR", u"Arkansas"),
    (u"CA", u"California"),
    (u"CO", u"Colorado"),
    (u"CT", u"Connecticut"),
    (u"DE", u"Delaware"),
    (u"FL", u"Florida"),
    (u"GA", u"Georgia"),
    (u"HI", u"Hawaii"),
    (u"ID", u"Idaho"),
    (u"IL", u"Illinois"),
    (u"IN", u"Indiana"),
    (u"IA", u"Iowa"),
    (u"KS", u"Kansas"),
    (u"KY", u"Kentucky"),
    (u"LA", u"Louisiana"),
    (u"ME", u"Maine"),
    (u"MD", u"Maryland"),
    (u"MA", u"Massachusetts"),
    (u"MI", u"Michigan"),
    (u"MN", u"Minnesota"),
    (u"MS", u"Mississippi"),
    (u"MO", u"Missouri"),
    (u"MT", u"Montana"),
    (u"NE", u"Nebraska"),
    (u"NV", u"Nevada"),
    (u"NH", u"New Hampshire"),
    (u"NJ", u"New Jersey"),
    (u"NM", u"New Mexico"),
    (u"NY", u"New York"),
    (u"NC", u"North Carolina"),
    (u"ND", u"North Dakota"),
    (u"OH", u"Ohio"),
    (u"OK", u"Oklahoma"),
    (u"OR", u"Oregon"),
    (u"PA", u"Pennsylvania"),
    (u"RI", u"Rhode Island"),
    (u"SC", u"South Carolina"),
    (u"SD", u"South Dakota"),
    (u"TN", u"Tennessee"),
    (u"TX", u"Texas"),
    (u"UT", u"Utah"),
    (u"VT", u"Vermont"),
    (u"VA", u"Virginia"),
    (u"WA", u"Washington"),
    (u"WV", u"West Virginia"),
    (u"WI", u"Wisconsin"),
    (u"WY", u"Wyoming"),
    (u"AS", u"American Samoa"),
    (u"DC", u"District of Columbia"),
    (u"FM", u"Federated States of Micronesia"),
    (u"GU", u"Guam"),
    (u"MH", u"Marshall Islands"),
    (u"MP", u"Northern Mariana Islands"),
    (u"PW", u"Palau"),
    (u"PR", u"Puerto Rico"),
    (u"VI", u"Virgin Islands")
)

GRADES = (
    ("K", "Kindergarden"),
    ("1", "1st Grade"),
    ("2", "2nd Grade"),
    ("3", "3rd Grade"),
    ("4", "4th Grade"),
    ("5", "5th Grade"),
    ("6", "6th Grade"),
    ("7", "7th Grade"),
    ("8", "8th Grade"),
    ("9", "9th Grade"),
    ("10", "10th Grade"),
    ("11", "11th Grade"),
    ("12", "12th Grade")
)

SECTORS = (
    ("edu", "Education"),
    ("health", "Health"),
    ("ced", "Community Economic Development"),
    ("env", "Environment"),
    ("yid", "Youth in Development"),
    ("agr", "Agriculture"),
    ("others", "Others")
)

KEYWORDS = (
    ("Dan", "Dance"),
    ("Mus", "Music"),
    ("WS", "Water Sanitation"),
    ("Sp", "Spanish"),
    ("Fr", "French"),
    ("Hol", "Holidays"),
    ("Cli", "Climate"),
    ("Ani", "Animals"),
    ("Fo", "Food"),
    ("Ag", "Agriculture"),
    ("Be", "Beekeeping")
)
